package com.yiwu.order_center_server.eduCenter.dao;


import com.yiwu.order_center_server.eduCenter.domain.Account;

public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_account
     *
     * @mbg.generated Tue Sep 06 17:36:27 CST 2022
     */
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_account
     *
     * @mbg.generated Tue Sep 06 17:36:27 CST 2022
     */
    int insertSelective(Account record);
}