package com.yiwu.order_center_server.eduCenter.dao;


import com.yiwu.order_center_server.eduCenter.domain.Teacher;

public interface TeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_teacher
     *
     * @mbg.generated Tue Sep 06 17:36:27 CST 2022
     */
    int insert(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_teacher
     *
     * @mbg.generated Tue Sep 06 17:36:27 CST 2022
     */
    int insertSelective(Teacher record);
}