package com.yiwu_order_center_server.dao;

import com.yiwu_order_center_server.domain.Account;

public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_account
     *
     * @mbg.generated Thu Sep 08 15:29:49 CST 2022
     */
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_account
     *
     * @mbg.generated Thu Sep 08 15:29:49 CST 2022
     */
    int insertSelective(Account record);
}