package com.yiwu_order_center_server.dao;

import com.yiwu_order_center_server.domain.Order;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    int insertSelective(Order record);
}