package com.yiwu_order_center_server.dao;

import com.yiwu_order_center_server.domain.RawMaterials;

public interface RawMaterialsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raw_materials
     *
     * @mbg.generated Mon Dec 20 15:02:40 CST 2021
     */
    int insert(RawMaterials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raw_materials
     *
     * @mbg.generated Mon Dec 20 15:02:40 CST 2021
     */
    int insertSelective(RawMaterials record);
}