package com.yiwu_order_center_server.dao;

import com.yiwu_order_center_server.domain.RawMaterialCategory;

public interface RawMaterialCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raw_material_category
     *
     * @mbg.generated Mon Dec 20 15:02:40 CST 2021
     */
    int insert(RawMaterialCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raw_material_category
     *
     * @mbg.generated Mon Dec 20 15:02:40 CST 2021
     */
    int insertSelective(RawMaterialCategory record);
}