package com.yiwu_order_center_server.dao;

import com.yiwu_order_center_server.domain.Teacher;

public interface TeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_teacher
     *
     * @mbg.generated Thu Sep 08 15:29:49 CST 2022
     */
    int insert(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_teacher
     *
     * @mbg.generated Thu Sep 08 15:29:49 CST 2022
     */
    int insertSelective(Teacher record);
}