package com.yiwu.order_center_server.eduCenter.domain;

import java.util.Date;

public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_account.id
     *
     * @mbg.generated Tue Sep 06 17:36:27 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_account.mobile_phone
     *
     * @mbg.generated Tue Sep 06 17:36:27 CST 2022
     */
    private String mobilePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_account.nick_name
     *
     * @mbg.generated Tue Sep 06 17:36:27 CST 2022
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_account.password
     *
     * @mbg.generated Tue Sep 06 17:36:27 CST 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_account.salt
     *
     * @mbg.generated Tue Sep 06 17:36:27 CST 2022
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_account.certification
     *
     * @mbg.generated Tue Sep 06 17:36:27 CST 2022
     */
    private Integer certification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_account.create_time
     *
     * @mbg.generated Tue Sep 06 17:36:27 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_account.update_time
     *
     * @mbg.generated Tue Sep 06 17:36:27 CST 2022
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_account.id
     *
     * @return the value of u_account.id
     *
     * @mbg.generated Tue Sep 06 17:36:27 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_account.id
     *
     * @param id the value for u_account.id
     *
     * @mbg.generated Tue Sep 06 17:36:27 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_account.mobile_phone
     *
     * @return the value of u_account.mobile_phone
     *
     * @mbg.generated Tue Sep 06 17:36:27 CST 2022
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_account.mobile_phone
     *
     * @param mobilePhone the value for u_account.mobile_phone
     *
     * @mbg.generated Tue Sep 06 17:36:27 CST 2022
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_account.nick_name
     *
     * @return the value of u_account.nick_name
     *
     * @mbg.generated Tue Sep 06 17:36:27 CST 2022
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_account.nick_name
     *
     * @param nickName the value for u_account.nick_name
     *
     * @mbg.generated Tue Sep 06 17:36:27 CST 2022
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_account.password
     *
     * @return the value of u_account.password
     *
     * @mbg.generated Tue Sep 06 17:36:27 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_account.password
     *
     * @param password the value for u_account.password
     *
     * @mbg.generated Tue Sep 06 17:36:27 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_account.salt
     *
     * @return the value of u_account.salt
     *
     * @mbg.generated Tue Sep 06 17:36:27 CST 2022
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_account.salt
     *
     * @param salt the value for u_account.salt
     *
     * @mbg.generated Tue Sep 06 17:36:27 CST 2022
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_account.certification
     *
     * @return the value of u_account.certification
     *
     * @mbg.generated Tue Sep 06 17:36:27 CST 2022
     */
    public Integer getCertification() {
        return certification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_account.certification
     *
     * @param certification the value for u_account.certification
     *
     * @mbg.generated Tue Sep 06 17:36:27 CST 2022
     */
    public void setCertification(Integer certification) {
        this.certification = certification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_account.create_time
     *
     * @return the value of u_account.create_time
     *
     * @mbg.generated Tue Sep 06 17:36:27 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_account.create_time
     *
     * @param createTime the value for u_account.create_time
     *
     * @mbg.generated Tue Sep 06 17:36:27 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_account.update_time
     *
     * @return the value of u_account.update_time
     *
     * @mbg.generated Tue Sep 06 17:36:27 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_account.update_time
     *
     * @param updateTime the value for u_account.update_time
     *
     * @mbg.generated Tue Sep 06 17:36:27 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}