package com.yiwu.order_center_server.domain;

import java.math.BigDecimal;
import java.util.Date;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.name
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.type
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.category_id
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.category_code
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    private String categoryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.status
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.pic
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.base_price
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    private BigDecimal basePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.sale_price
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    private BigDecimal salePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.sale_pattern
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    private Integer salePattern;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.on_time
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    private Date onTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.off_time
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    private Date offTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.open_tag
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    private Integer openTag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.sort
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.is_del
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    private Integer isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.ucode
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    private String ucode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.create_user_id
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    private Long createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.update_user_id
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    private Long updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.create_time
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.update_time
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.branch_id
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    private Long branchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.saas_id
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    private Long saasId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.name
     *
     * @return the value of goods.name
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.name
     *
     * @param name the value for goods.name
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.type
     *
     * @return the value of goods.type
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.type
     *
     * @param type the value for goods.type
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.category_id
     *
     * @return the value of goods.category_id
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.category_id
     *
     * @param categoryId the value for goods.category_id
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.category_code
     *
     * @return the value of goods.category_code
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public String getCategoryCode() {
        return categoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.category_code
     *
     * @param categoryCode the value for goods.category_code
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public void setCategoryCode(String categoryCode) {
        this.categoryCode = categoryCode == null ? null : categoryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.status
     *
     * @return the value of goods.status
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.status
     *
     * @param status the value for goods.status
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.pic
     *
     * @return the value of goods.pic
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.pic
     *
     * @param pic the value for goods.pic
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.base_price
     *
     * @return the value of goods.base_price
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public BigDecimal getBasePrice() {
        return basePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.base_price
     *
     * @param basePrice the value for goods.base_price
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public void setBasePrice(BigDecimal basePrice) {
        this.basePrice = basePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.sale_price
     *
     * @return the value of goods.sale_price
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public BigDecimal getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.sale_price
     *
     * @param salePrice the value for goods.sale_price
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public void setSalePrice(BigDecimal salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.sale_pattern
     *
     * @return the value of goods.sale_pattern
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public Integer getSalePattern() {
        return salePattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.sale_pattern
     *
     * @param salePattern the value for goods.sale_pattern
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public void setSalePattern(Integer salePattern) {
        this.salePattern = salePattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.on_time
     *
     * @return the value of goods.on_time
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public Date getOnTime() {
        return onTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.on_time
     *
     * @param onTime the value for goods.on_time
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public void setOnTime(Date onTime) {
        this.onTime = onTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.off_time
     *
     * @return the value of goods.off_time
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public Date getOffTime() {
        return offTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.off_time
     *
     * @param offTime the value for goods.off_time
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public void setOffTime(Date offTime) {
        this.offTime = offTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.open_tag
     *
     * @return the value of goods.open_tag
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public Integer getOpenTag() {
        return openTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.open_tag
     *
     * @param openTag the value for goods.open_tag
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public void setOpenTag(Integer openTag) {
        this.openTag = openTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.sort
     *
     * @return the value of goods.sort
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.sort
     *
     * @param sort the value for goods.sort
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.is_del
     *
     * @return the value of goods.is_del
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.is_del
     *
     * @param isDel the value for goods.is_del
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.ucode
     *
     * @return the value of goods.ucode
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public String getUcode() {
        return ucode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.ucode
     *
     * @param ucode the value for goods.ucode
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public void setUcode(String ucode) {
        this.ucode = ucode == null ? null : ucode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.create_user_id
     *
     * @return the value of goods.create_user_id
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.create_user_id
     *
     * @param createUserId the value for goods.create_user_id
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.update_user_id
     *
     * @return the value of goods.update_user_id
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.update_user_id
     *
     * @param updateUserId the value for goods.update_user_id
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.create_time
     *
     * @return the value of goods.create_time
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.create_time
     *
     * @param createTime the value for goods.create_time
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.update_time
     *
     * @return the value of goods.update_time
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.update_time
     *
     * @param updateTime the value for goods.update_time
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.branch_id
     *
     * @return the value of goods.branch_id
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public Long getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.branch_id
     *
     * @param branchId the value for goods.branch_id
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public void setBranchId(Long branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.saas_id
     *
     * @return the value of goods.saas_id
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public Long getSaasId() {
        return saasId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.saas_id
     *
     * @param saasId the value for goods.saas_id
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    public void setSaasId(Long saasId) {
        this.saasId = saasId;
    }
}