package com.yiwu.order_center_server.domain;

import java.util.Date;

public class RawMaterials {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raw_materials.id
     *
     * @mbg.generated Mon Dec 20 14:50:10 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raw_materials.name
     *
     * @mbg.generated Mon Dec 20 14:50:10 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raw_materials.catogory_id
     *
     * @mbg.generated Mon Dec 20 14:50:10 CST 2021
     */
    private Long catogoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raw_materials.catogory_code
     *
     * @mbg.generated Mon Dec 20 14:50:10 CST 2021
     */
    private String catogoryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raw_materials.status
     *
     * @mbg.generated Mon Dec 20 14:50:10 CST 2021
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raw_materials.is_del
     *
     * @mbg.generated Mon Dec 20 14:50:10 CST 2021
     */
    private Integer isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raw_materials.create_time
     *
     * @mbg.generated Mon Dec 20 14:50:10 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raw_materials.update_time
     *
     * @mbg.generated Mon Dec 20 14:50:10 CST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column raw_materials.id
     *
     * @return the value of raw_materials.id
     *
     * @mbg.generated Mon Dec 20 14:50:10 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column raw_materials.id
     *
     * @param id the value for raw_materials.id
     *
     * @mbg.generated Mon Dec 20 14:50:10 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column raw_materials.name
     *
     * @return the value of raw_materials.name
     *
     * @mbg.generated Mon Dec 20 14:50:10 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column raw_materials.name
     *
     * @param name the value for raw_materials.name
     *
     * @mbg.generated Mon Dec 20 14:50:10 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column raw_materials.catogory_id
     *
     * @return the value of raw_materials.catogory_id
     *
     * @mbg.generated Mon Dec 20 14:50:10 CST 2021
     */
    public Long getCatogoryId() {
        return catogoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column raw_materials.catogory_id
     *
     * @param catogoryId the value for raw_materials.catogory_id
     *
     * @mbg.generated Mon Dec 20 14:50:10 CST 2021
     */
    public void setCatogoryId(Long catogoryId) {
        this.catogoryId = catogoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column raw_materials.catogory_code
     *
     * @return the value of raw_materials.catogory_code
     *
     * @mbg.generated Mon Dec 20 14:50:10 CST 2021
     */
    public String getCatogoryCode() {
        return catogoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column raw_materials.catogory_code
     *
     * @param catogoryCode the value for raw_materials.catogory_code
     *
     * @mbg.generated Mon Dec 20 14:50:10 CST 2021
     */
    public void setCatogoryCode(String catogoryCode) {
        this.catogoryCode = catogoryCode == null ? null : catogoryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column raw_materials.status
     *
     * @return the value of raw_materials.status
     *
     * @mbg.generated Mon Dec 20 14:50:10 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column raw_materials.status
     *
     * @param status the value for raw_materials.status
     *
     * @mbg.generated Mon Dec 20 14:50:10 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column raw_materials.is_del
     *
     * @return the value of raw_materials.is_del
     *
     * @mbg.generated Mon Dec 20 14:50:10 CST 2021
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column raw_materials.is_del
     *
     * @param isDel the value for raw_materials.is_del
     *
     * @mbg.generated Mon Dec 20 14:50:10 CST 2021
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column raw_materials.create_time
     *
     * @return the value of raw_materials.create_time
     *
     * @mbg.generated Mon Dec 20 14:50:10 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column raw_materials.create_time
     *
     * @param createTime the value for raw_materials.create_time
     *
     * @mbg.generated Mon Dec 20 14:50:10 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column raw_materials.update_time
     *
     * @return the value of raw_materials.update_time
     *
     * @mbg.generated Mon Dec 20 14:50:10 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column raw_materials.update_time
     *
     * @param updateTime the value for raw_materials.update_time
     *
     * @mbg.generated Mon Dec 20 14:50:10 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}