package com.yiwu.order_center_server.dao;

import com.yiwu.order_center_server.domain.Goods;

public interface GoodsDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    int insert(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Mon Dec 20 11:44:35 CST 2021
     */
    int insertSelective(Goods record);
}