package com.yiwu.order_center_server.dao;

import com.yiwu.order_center_server.domain.RawMaterials;

public interface RawMaterialsDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raw_materials
     *
     * @mbg.generated Mon Dec 20 14:50:10 CST 2021
     */
    int insert(RawMaterials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raw_materials
     *
     * @mbg.generated Mon Dec 20 14:50:10 CST 2021
     */
    int insertSelective(RawMaterials record);
}