package com.yiwu_order_center_server.domain;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_type
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    private Integer orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_no
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user_id
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.status
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.real_pay
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    private BigDecimal realPay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.total_money
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    private BigDecimal totalMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_time
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    private Date orderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.paid_time
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    private Date paidTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.cancel_time
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    private Date cancelTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.expire_time
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    private Date expireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.create_user_id
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    private Long createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.create_time
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.update_user_id
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    private Long updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.update_time
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.saas_id
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    private Long saasId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.branch_id
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    private Long branchId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_type
     *
     * @return the value of order.order_type
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_type
     *
     * @param orderType the value for order.order_type
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_no
     *
     * @return the value of order.order_no
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_no
     *
     * @param orderNo the value for order.order_no
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.user_id
     *
     * @return the value of order.user_id
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.user_id
     *
     * @param userId the value for order.user_id
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.status
     *
     * @return the value of order.status
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.status
     *
     * @param status the value for order.status
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.real_pay
     *
     * @return the value of order.real_pay
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public BigDecimal getRealPay() {
        return realPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.real_pay
     *
     * @param realPay the value for order.real_pay
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public void setRealPay(BigDecimal realPay) {
        this.realPay = realPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.total_money
     *
     * @return the value of order.total_money
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public BigDecimal getTotalMoney() {
        return totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.total_money
     *
     * @param totalMoney the value for order.total_money
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public void setTotalMoney(BigDecimal totalMoney) {
        this.totalMoney = totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_time
     *
     * @return the value of order.order_time
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_time
     *
     * @param orderTime the value for order.order_time
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.paid_time
     *
     * @return the value of order.paid_time
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public Date getPaidTime() {
        return paidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.paid_time
     *
     * @param paidTime the value for order.paid_time
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public void setPaidTime(Date paidTime) {
        this.paidTime = paidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.cancel_time
     *
     * @return the value of order.cancel_time
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public Date getCancelTime() {
        return cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.cancel_time
     *
     * @param cancelTime the value for order.cancel_time
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public void setCancelTime(Date cancelTime) {
        this.cancelTime = cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.expire_time
     *
     * @return the value of order.expire_time
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.expire_time
     *
     * @param expireTime the value for order.expire_time
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.create_user_id
     *
     * @return the value of order.create_user_id
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.create_user_id
     *
     * @param createUserId the value for order.create_user_id
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.create_time
     *
     * @return the value of order.create_time
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.create_time
     *
     * @param createTime the value for order.create_time
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.update_user_id
     *
     * @return the value of order.update_user_id
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.update_user_id
     *
     * @param updateUserId the value for order.update_user_id
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.update_time
     *
     * @return the value of order.update_time
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.update_time
     *
     * @param updateTime the value for order.update_time
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.saas_id
     *
     * @return the value of order.saas_id
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public Long getSaasId() {
        return saasId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.saas_id
     *
     * @param saasId the value for order.saas_id
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public void setSaasId(Long saasId) {
        this.saasId = saasId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.branch_id
     *
     * @return the value of order.branch_id
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public Long getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.branch_id
     *
     * @param branchId the value for order.branch_id
     *
     * @mbg.generated Thu Dec 31 11:11:58 CST 2020
     */
    public void setBranchId(Long branchId) {
        this.branchId = branchId;
    }
}