package com.yiwu_order_center_server.domain;

import java.util.Date;

public class Teacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_teacher.id
     *
     * @mbg.generated Thu Sep 08 15:29:49 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_teacher.account_id
     *
     * @mbg.generated Thu Sep 08 15:29:49 CST 2022
     */
    private Long accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_teacher.name
     *
     * @mbg.generated Thu Sep 08 15:29:49 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_teacher.sex
     *
     * @mbg.generated Thu Sep 08 15:29:49 CST 2022
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_teacher.birthday
     *
     * @mbg.generated Thu Sep 08 15:29:49 CST 2022
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_teacher.pic
     *
     * @mbg.generated Thu Sep 08 15:29:49 CST 2022
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_teacher.id_card
     *
     * @mbg.generated Thu Sep 08 15:29:49 CST 2022
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_teacher.create_time
     *
     * @mbg.generated Thu Sep 08 15:29:49 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_teacher.update_time
     *
     * @mbg.generated Thu Sep 08 15:29:49 CST 2022
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_teacher.id
     *
     * @return the value of u_teacher.id
     *
     * @mbg.generated Thu Sep 08 15:29:49 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_teacher.id
     *
     * @param id the value for u_teacher.id
     *
     * @mbg.generated Thu Sep 08 15:29:49 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_teacher.account_id
     *
     * @return the value of u_teacher.account_id
     *
     * @mbg.generated Thu Sep 08 15:29:49 CST 2022
     */
    public Long getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_teacher.account_id
     *
     * @param accountId the value for u_teacher.account_id
     *
     * @mbg.generated Thu Sep 08 15:29:49 CST 2022
     */
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_teacher.name
     *
     * @return the value of u_teacher.name
     *
     * @mbg.generated Thu Sep 08 15:29:49 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_teacher.name
     *
     * @param name the value for u_teacher.name
     *
     * @mbg.generated Thu Sep 08 15:29:49 CST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_teacher.sex
     *
     * @return the value of u_teacher.sex
     *
     * @mbg.generated Thu Sep 08 15:29:49 CST 2022
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_teacher.sex
     *
     * @param sex the value for u_teacher.sex
     *
     * @mbg.generated Thu Sep 08 15:29:49 CST 2022
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_teacher.birthday
     *
     * @return the value of u_teacher.birthday
     *
     * @mbg.generated Thu Sep 08 15:29:49 CST 2022
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_teacher.birthday
     *
     * @param birthday the value for u_teacher.birthday
     *
     * @mbg.generated Thu Sep 08 15:29:49 CST 2022
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_teacher.pic
     *
     * @return the value of u_teacher.pic
     *
     * @mbg.generated Thu Sep 08 15:29:49 CST 2022
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_teacher.pic
     *
     * @param pic the value for u_teacher.pic
     *
     * @mbg.generated Thu Sep 08 15:29:49 CST 2022
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_teacher.id_card
     *
     * @return the value of u_teacher.id_card
     *
     * @mbg.generated Thu Sep 08 15:29:49 CST 2022
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_teacher.id_card
     *
     * @param idCard the value for u_teacher.id_card
     *
     * @mbg.generated Thu Sep 08 15:29:49 CST 2022
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_teacher.create_time
     *
     * @return the value of u_teacher.create_time
     *
     * @mbg.generated Thu Sep 08 15:29:49 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_teacher.create_time
     *
     * @param createTime the value for u_teacher.create_time
     *
     * @mbg.generated Thu Sep 08 15:29:49 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_teacher.update_time
     *
     * @return the value of u_teacher.update_time
     *
     * @mbg.generated Thu Sep 08 15:29:49 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_teacher.update_time
     *
     * @param updateTime the value for u_teacher.update_time
     *
     * @mbg.generated Thu Sep 08 15:29:49 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}